version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/images/obsidian-sync"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/images/reconciler"
    schedule:
      interval: "weekly"
