version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/images/obsidian-sync"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/images/reconciler"
    schedule:
      interval: "weekly"
